const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{实体: 0},
	{ice: 0},
	{闪烁: 0},
	{fragileIce: 0},
	{snowman: 0},
	{平台: 0},
	{镜头跟随: 0},
	{dog: 0},
	{键盘: 0},
	{newDog: 0},
	{bone: 0},
	{star: 0},
	{door: 0},
	{文本: 0},
	{按钮: 0},
	{mashroom: 0},
	{mashroom2: 0},
	{starNum: 0},
	{snowmanNum: 0},
	{boneNum: 0}
];

self.InstanceType = {
	ice: class extends self.ITiledBackgroundInstance {},
	fragileIce: class extends self.ITiledBackgroundInstance {},
	snowman: class extends self.ISpriteInstance {},
	dog: class extends self.ISpriteInstance {},
	键盘: class extends self.IInstance {},
	newDog: class extends self.ISpriteInstance {},
	bone: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	door: class extends self.ISpriteInstance {},
	文本: class extends self.ITextInstance {},
	按钮: class extends self.IButtonInstance {},
	mashroom: class extends self.ISpriteInstance {},
	mashroom2: class extends self.ISpriteInstance {}
}